name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Build source code
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm i
    - run: npm run build

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "./build/index-bundle.js"
        target: "/bots/select-star/index-bundle.js"
